// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import QuantityChangersController from "./quantity_changers_controller"
application.register("quantity-changer", QuantityChangersController)

import OpenModalsController from "./open_modal_controller"
application.register("open-modal", OpenModalsController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)
