version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@5.2.0
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      - node/install:
          install-yarn: true
          node-version: '20.12.2'
      - run: node --version
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.2.2
      - image: cimg/postgres:15.6
        environment:
          POSTGRES_USER: individual-clothes
          POSTGRES_DB: individual_working_clothes_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: individual-clothes
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install:
          install-yarn: true
          node-version: '20.12.2'
      - run: node --version
      - browser-tools/install-chrome:
        chrome-version: 125.0.6422.60
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
